import "./globals.css";
import type { Metadata } from "next";
import React from "react";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <SidebarProvider>
          <SidebarTrigger />
          {children}
        </SidebarProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
