import "./globals.css";
import type { Metadata } from "next";
import React from "react";

import localFont from "next/font/local";
import { React95Styles } from "./react-95-styles";

const msSansSerif = localFont({
  src: [
    {
      path: "./../public/ms_sans_serif.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../public/ms_sans_serif.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-ms-sans-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${msSansSerif.variable}`}>
        <React95Styles>{children}</React95Styles>
      </body>
    </html>
  );
}
